import {
    SearchOutlined,
    MenuOutlined,
    SettingsOutlined,
    CloseOutlined,
    AddOutlined,
    CheckCircle,
    Info,
    Error,
    FavoriteBorderOutlined,
    Favorite,
    StarOutlineOutlined,
    Star,
    ChevronLeftOutlined,
    ChevronRightOutlined,
    AppsRounded,
    Delete,
    LocationOnOutlined,
    ExploreOutlined,
    AccountCircleOutlined,
    TuneOutlined,
    ShareOutlined,
    NotificationsOutlined,
    HelpOutlined,
    LanguageOutlined,
    ChatBubbleOutlineOutlined,
    CalendarTodayOutlined,
    EventBusyOutlined,
    WorkspacePremiumOutlined,
    VerifiedUserOutlined,
    GppBadOutlined,
    MapOutlined,
    BarChartOutlined,
    Groups,
    HandshakeOutlined,
    ArrowOutwardOutlined,
    CallOutlined,
    MailOutlineOutlined,
    SchoolOutlined,
    PaletteOutlined,
    LocalBarOutlined,
    ScheduleOutlined,
    SentimentSatisfiedAltRounded,
    EventAvailableOutlined,
    QuickreplyOutlined,
    SellOutlined,
    PsychologyAltOutlined,
    AssignmentIndOutlined
} from "@mui/icons-material";

export const AppIcons = {
    search: <SearchOutlined />,
    menu: <MenuOutlined />,
    settings: <SettingsOutlined />,
    close: <CloseOutlined />,
    add: <AddOutlined />,
    success: <CheckCircle />,
    info: <Info />,
    error: <Error />,
    favorite: <FavoriteBorderOutlined />,
    favorite_filled: <Favorite />,
    star: <StarOutlineOutlined />,
    star_filled: <Star />,
    chevron_left: <ChevronLeftOutlined />,
    chevron_right: <ChevronRightOutlined />,
    apps: <AppsRounded />,
    delete: <Delete />,
    location: <LocationOnOutlined />,
    explore: <ExploreOutlined />,
    account: <AccountCircleOutlined />,
    filter: <TuneOutlined style={{ transform: "rotate(90deg)" }} />,
    share: <ShareOutlined />,
    notification: <NotificationsOutlined />,
    help: <HelpOutlined />,
    language: <LanguageOutlined />,
    message: <ChatBubbleOutlineOutlined />,
    calendar: <CalendarTodayOutlined />,
    calendar_cancel: <EventBusyOutlined />,
    achievement: <WorkspacePremiumOutlined />,
    verified: <VerifiedUserOutlined />,
    unverified: <GppBadOutlined />,
    map: <MapOutlined />,
    chart: <BarChartOutlined />,
    group: <Groups />,
    handshake: <HandshakeOutlined />,
    arrow_outward: <ArrowOutwardOutlined />,
    call: <CallOutlined />,
    mail: <MailOutlineOutlined />,
    education_service: <SchoolOutlined />,
    art_service: <PaletteOutlined />,
    event_service: <LocalBarOutlined />,
    punctuality: <ScheduleOutlined />,
    friendliness: <SentimentSatisfiedAltRounded />,
    availability: <EventAvailableOutlined />,
    quick_reply: <QuickreplyOutlined />,
    price_quality: <SellOutlined />,
    knowledge: <PsychologyAltOutlined />,
    personal_presentation: <AssignmentIndOutlined />,
};

export type IconName = keyof typeof AppIcons;